# disable in production:  
# local_backend: true
# command to run a local Decap instance: npx-decap-server

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

media_folder: "public/upload"
public_folder: "/upload"

site_url: https://walleyemaster.com

media_library:
  name: cloudinary
  # output_filename_only: true
  config:
    cloud_name: <YOUR_CLOUD_NAME_HERE>
    api_key: <YOUR_API_KEY_HERE> 


# SEO anchor:
seo: &seo
  name: "SEOmetaData"
  label: "SEO"
  widget: "object"
  collapsed: true
  fields: 
    - { name: "metaTitle", label: "SEO Title", widget: "string", default: "{{ title }}", required: true }
    - { name: "metaDescription", label: "SEO Description", widget: "string", pattern: [".{20,160}", "between 20 and 160 characters"], required: true, hint: "must be between 20 and 160 characters" }
    - { name: "metaImage", label: "SEO image", widget: "image"}
    - { name: "keywords", label: "keywords", widget: "string", hint: "keywords are comma seperated", required: false }



collections:
  # BLOG POSTS
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string", required: true }
      - { name: "description", label: "Description", widget: "text", required: true, hint: "Brief description for SEO and previews" }
      - { name: "featuredImage", label: "Featured Image", widget: "image", required: false }
      - { name: "publishedAt", label: "Published Date", widget: "datetime", required: true }
      - { name: "author", label: "Author", widget: "string", default: "Walleye Master Team" }
      - { name: "categories", label: "Categories", widget: "list", allow_add: true, collapsed: false, field: { label: "Category", name: "category", widget: "string" } }
      - { name: "tags", label: "Tags", widget: "list", allow_add: true, collapsed: false, field: { label: "Tag", name: "tag", widget: "string" } }
      - { name: "readingTime", label: "Reading Time (minutes)", widget: "number", value_type: "int", min: 1, max: 60, required: false }
      - { name: "draft", label: "Draft", widget: "boolean", default: false }
      - { name: "content", label: "Content", widget: "markdown", required: true }
      - *seo

  - name: "globalContent"
    label: "global content"
    files: 
      - label: "buttons"
        name: "buttons"
        file: "content/components/buttons.md"    
        fields: 
          - label: "next"
            name: "next"
            widget: "string"        
          - label: "previous"
            name: "previous"
            widget: "string"        
          - label: "close"
            name: "close"
            widget: "string"        
          - label: "article: more"
            name: "article"
            widget: "string"
            default: "read more"
          - label: "form: send"
            name: "send"
            widget: "string"
        
  # SINGLE PAGES
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        file: "content/pages/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
          - *seo
      - name: "typography"
        label: "Typography"
        file: "content/pages/typography.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }


